name       : gprename
version    : '20230429'
release    : 7
source     :
    - https://sourceforge.net/projects/gprename/files/gprename/20230429/gprename-20230429.zip/download : bb6ffa81db7bca22030377ce60d28a5eaa02cea975252b5639ca9f7ea17c2002
homepage   : https://gprename.sourceforge.net
license    : GPL-3.0-or-later
component  : system.utils
summary    : GPRename is a complete batch renamer for files and directories
description: |
    GPRename is a complete batch renamer for files and directories.
rundeps    :
    - perl-gettext
    - perl-glib
    - perl-gtk3
    - perl-libintl
    - perl-pango
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-gprename-Makefile.patch
    sed 's#/usr/share/icons/gprename.png#/usr/share/pixmaps/gprename.png#' -i bin/gprename
install    : |
    %make_install PREFIX=/usr
    sed -i 's|/usr/local|/usr|' $installdir/usr/bin/gprename

