name       : gprename
version    : '20210415'
release    : 3
source     :
    - https://sourceforge.net/projects/gprename/files/gprename/20210415/gprename-20210415.tar.bz2/download : 9b86979a7b8d884ad6b2b9ff63c9c1b383b9f44368d4164cc533ac92d1f95382
homepage   : http://gprename.sourceforge.net
license    : GPL-3.0-or-later
component  : system.utils
summary    : GPRename is a complete batch renamer for files and directories
description: |
    GPRename is a complete batch renamer for files and directories.
rundeps    :
    - perl-gettext
    - perl-glib
    - perl-gtk3
    - perl-libintl
    - perl-pango
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-gprename-Makefile.patch
install    : |
    %make_install PREFIX=/usr
    sed -i 's|/usr/local|/usr|' $installdir/usr/bin/gprename
    sed -i 's|/usr/local|/usr|' $installdir/usr/share/applications/gprename-nautilus-actions.xml
    sed -i 's|/usr/share/pixmaps/gprename|/usr/share/icons|' $installdir/usr/share/applications/gprename-nautilus-actions.xml

