name       : gprename
version    : '20190221'
release    : 2
source     :
    - https://liquidtelecom.dl.sourceforge.net/project/gprename/gprename/20190221/gprename-20190221.tar.bz2 : 7558c4e9738a549c661712d2a84a446e5a803725e66a62edc6ace42737413ac4
homepage   : http://gprename.sourceforge.net
license    : GPL-3.0-or-later
component  : system.utils
summary    : GPRename is a complete batch renamer for files and directories
description: |
    GPRename is a complete batch renamer for files and directories.
rundeps    :
    - perl-gettext
    - perl-glib
    - perl-gtk2
    - perl-libintl
    - perl-pango
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-gprename-Makefile.patch
install    : |
    %make_install PREFIX=/usr
    sed -i 's|/usr/local|/usr|' $installdir/usr/bin/gprename
    sed -i 's|/usr/local|/usr|' $installdir/usr/share/applications/gprename-nautilus-actions.xml
    sed -i 's|/usr/share/pixmaps/gprename|/usr/share/icons|' $installdir/usr/share/applications/gprename-nautilus-actions.xml

